on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'jp_birthday/*'
      - 'tests/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
        # python-version: [3.7]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@master
      # - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: |
          ls -la
          make test-all

      - uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella # optional

          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
          # files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
